name: Build and Release Binary

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build binary with Nuitka
        run: |
          pip install rembg pillow nuitka ordered-set
          nuitka --onefile --standalone --output-filename=bluepaw bluepaw.py

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: bluepaw
